/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PostParrainageDRouteImport } from './routes/post-parrainage-d'
import { Route as OpengraphImageRouteImport } from './routes/opengraph-image'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as GardeChienVannesRouteImport } from './routes/garde-chien-vannes'
import { Route as GardeChatVannesRouteImport } from './routes/garde-chat-vannes'
import { Route as DsRouteImport } from './routes/ds'
import { Route as CarteVersoV2RouteImport } from './routes/carte-verso-v2'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as UploadsSplatRouteImport } from './routes/uploads/$'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as PublicVisitesChienVannesRouteImport } from './routes/_public/visites-chien-vannes'
import { Route as PublicVisitesChatVannesRouteImport } from './routes/_public/visites-chat-vannes'
import { Route as PublicPromenadeChienVannesRouteImport } from './routes/_public/promenade-chien-vannes'
import { Route as PublicPensionChienVannesRouteImport } from './routes/_public/pension-chien-vannes'
import { Route as PublicPensionChatVannesRouteImport } from './routes/_public/pension-chat-vannes'
import { Route as PublicGardeADomicileVannesRouteImport } from './routes/_public/garde-a-domicile-vannes'
import { Route as PublicEquitationVannesRouteImport } from './routes/_public/equitation-vannes'
import { Route as AdminDashboardRouteRouteImport } from './routes/admin/dashboard/route'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as SChannelChar123CampaignChar125RouteImport } from './routes/s.$channel.{-$campaign}'
import { Route as OgServiceSlugOpengraphImageRouteImport } from './routes/og-service/$slug/opengraph-image'
import { Route as ApiAdminReviewsRouteImport } from './routes/api/admin/reviews'
import { Route as ApiAdminGalerieRouteImport } from './routes/api/admin/galerie'
import { Route as ApiAdminAuthRouteImport } from './routes/api/admin/auth'
import { Route as AdminDashboardTemoignagesRouteImport } from './routes/admin/dashboard/temoignages'
import { Route as AdminDashboardGalerieRouteImport } from './routes/admin/dashboard/galerie'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PostParrainageDRoute = PostParrainageDRouteImport.update({
  id: '/post-parrainage-d',
  path: '/post-parrainage-d',
  getParentRoute: () => rootRouteImport,
} as any)
const OpengraphImageRoute = OpengraphImageRouteImport.update({
  id: '/opengraph-image',
  path: '/opengraph-image',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const GardeChienVannesRoute = GardeChienVannesRouteImport.update({
  id: '/garde-chien-vannes',
  path: '/garde-chien-vannes',
  getParentRoute: () => rootRouteImport,
} as any)
const GardeChatVannesRoute = GardeChatVannesRouteImport.update({
  id: '/garde-chat-vannes',
  path: '/garde-chat-vannes',
  getParentRoute: () => rootRouteImport,
} as any)
const DsRoute = DsRouteImport.update({
  id: '/ds',
  path: '/ds',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteVersoV2Route = CarteVersoV2RouteImport.update({
  id: '/carte-verso-v2',
  path: '/carte-verso-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicVisitesChienVannesRoute =
  PublicVisitesChienVannesRouteImport.update({
    id: '/visites-chien-vannes',
    path: '/visites-chien-vannes',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicVisitesChatVannesRoute = PublicVisitesChatVannesRouteImport.update({
  id: '/visites-chat-vannes',
  path: '/visites-chat-vannes',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPromenadeChienVannesRoute =
  PublicPromenadeChienVannesRouteImport.update({
    id: '/promenade-chien-vannes',
    path: '/promenade-chien-vannes',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicPensionChienVannesRoute =
  PublicPensionChienVannesRouteImport.update({
    id: '/pension-chien-vannes',
    path: '/pension-chien-vannes',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicPensionChatVannesRoute = PublicPensionChatVannesRouteImport.update({
  id: '/pension-chat-vannes',
  path: '/pension-chat-vannes',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGardeADomicileVannesRoute =
  PublicGardeADomicileVannesRouteImport.update({
    id: '/garde-a-domicile-vannes',
    path: '/garde-a-domicile-vannes',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicEquitationVannesRoute = PublicEquitationVannesRouteImport.update({
  id: '/equitation-vannes',
  path: '/equitation-vannes',
  getParentRoute: () => PublicRoute,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const SChannelChar123CampaignChar125Route =
  SChannelChar123CampaignChar125RouteImport.update({
    id: '/s/$channel/{-$campaign}',
    path: '/s/$channel/{-$campaign}',
    getParentRoute: () => rootRouteImport,
  } as any)
const OgServiceSlugOpengraphImageRoute =
  OgServiceSlugOpengraphImageRouteImport.update({
    id: '/og-service/$slug/opengraph-image',
    path: '/og-service/$slug/opengraph-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminReviewsRoute = ApiAdminReviewsRouteImport.update({
  id: '/api/admin/reviews',
  path: '/api/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGalerieRoute = ApiAdminGalerieRouteImport.update({
  id: '/api/admin/galerie',
  path: '/api/admin/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthRoute = ApiAdminAuthRouteImport.update({
  id: '/api/admin/auth',
  path: '/api/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardTemoignagesRoute =
  AdminDashboardTemoignagesRouteImport.update({
    id: '/temoignages',
    path: '/temoignages',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardGalerieRoute = AdminDashboardGalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/': typeof PublicIndexRoute
  '/carte-verso-v2': typeof CarteVersoV2Route
  '/ds': typeof DsRoute
  '/garde-chat-vannes': typeof GardeChatVannesRoute
  '/garde-chien-vannes': typeof GardeChienVannesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/post-parrainage-d': typeof PostParrainageDRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/equitation-vannes': typeof PublicEquitationVannesRoute
  '/garde-a-domicile-vannes': typeof PublicGardeADomicileVannesRoute
  '/pension-chat-vannes': typeof PublicPensionChatVannesRoute
  '/pension-chien-vannes': typeof PublicPensionChienVannesRoute
  '/promenade-chien-vannes': typeof PublicPromenadeChienVannesRoute
  '/visites-chat-vannes': typeof PublicVisitesChatVannesRoute
  '/visites-chien-vannes': typeof PublicVisitesChienVannesRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/contact': typeof ApiContactRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin/dashboard/galerie': typeof AdminDashboardGalerieRoute
  '/admin/dashboard/temoignages': typeof AdminDashboardTemoignagesRoute
  '/api/admin/auth': typeof ApiAdminAuthRoute
  '/api/admin/galerie': typeof ApiAdminGalerieRoute
  '/api/admin/reviews': typeof ApiAdminReviewsRoute
  '/og-service/$slug/opengraph-image': typeof OgServiceSlugOpengraphImageRoute
  '/s/$channel/{-$campaign}': typeof SChannelChar123CampaignChar125Route
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteRouteWithChildren
  '/carte-verso-v2': typeof CarteVersoV2Route
  '/ds': typeof DsRoute
  '/garde-chat-vannes': typeof GardeChatVannesRoute
  '/garde-chien-vannes': typeof GardeChienVannesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/post-parrainage-d': typeof PostParrainageDRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/equitation-vannes': typeof PublicEquitationVannesRoute
  '/garde-a-domicile-vannes': typeof PublicGardeADomicileVannesRoute
  '/pension-chat-vannes': typeof PublicPensionChatVannesRoute
  '/pension-chien-vannes': typeof PublicPensionChienVannesRoute
  '/promenade-chien-vannes': typeof PublicPromenadeChienVannesRoute
  '/visites-chat-vannes': typeof PublicVisitesChatVannesRoute
  '/visites-chien-vannes': typeof PublicVisitesChienVannesRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/contact': typeof ApiContactRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/': typeof PublicIndexRoute
  '/admin/dashboard/galerie': typeof AdminDashboardGalerieRoute
  '/admin/dashboard/temoignages': typeof AdminDashboardTemoignagesRoute
  '/api/admin/auth': typeof ApiAdminAuthRoute
  '/api/admin/galerie': typeof ApiAdminGalerieRoute
  '/api/admin/reviews': typeof ApiAdminReviewsRoute
  '/og-service/$slug/opengraph-image': typeof OgServiceSlugOpengraphImageRoute
  '/s/$channel/{-$campaign}': typeof SChannelChar123CampaignChar125Route
  '/admin/dashboard': typeof AdminDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/carte-verso-v2': typeof CarteVersoV2Route
  '/ds': typeof DsRoute
  '/garde-chat-vannes': typeof GardeChatVannesRoute
  '/garde-chien-vannes': typeof GardeChienVannesRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/opengraph-image': typeof OpengraphImageRoute
  '/post-parrainage-d': typeof PostParrainageDRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/_public/equitation-vannes': typeof PublicEquitationVannesRoute
  '/_public/garde-a-domicile-vannes': typeof PublicGardeADomicileVannesRoute
  '/_public/pension-chat-vannes': typeof PublicPensionChatVannesRoute
  '/_public/pension-chien-vannes': typeof PublicPensionChienVannesRoute
  '/_public/promenade-chien-vannes': typeof PublicPromenadeChienVannesRoute
  '/_public/visites-chat-vannes': typeof PublicVisitesChatVannesRoute
  '/_public/visites-chien-vannes': typeof PublicVisitesChienVannesRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/contact': typeof ApiContactRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/dashboard/galerie': typeof AdminDashboardGalerieRoute
  '/admin/dashboard/temoignages': typeof AdminDashboardTemoignagesRoute
  '/api/admin/auth': typeof ApiAdminAuthRoute
  '/api/admin/galerie': typeof ApiAdminGalerieRoute
  '/api/admin/reviews': typeof ApiAdminReviewsRoute
  '/og-service/$slug/opengraph-image': typeof OgServiceSlugOpengraphImageRoute
  '/s/$channel/{-$campaign}': typeof SChannelChar123CampaignChar125Route
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/'
    | '/carte-verso-v2'
    | '/ds'
    | '/garde-chat-vannes'
    | '/garde-chien-vannes'
    | '/llms.txt'
    | '/opengraph-image'
    | '/post-parrainage-d'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/dashboard'
    | '/equitation-vannes'
    | '/garde-a-domicile-vannes'
    | '/pension-chat-vannes'
    | '/pension-chien-vannes'
    | '/promenade-chien-vannes'
    | '/visites-chat-vannes'
    | '/visites-chien-vannes'
    | '/admin/login'
    | '/api/contact'
    | '/uploads/$'
    | '/admin/dashboard/galerie'
    | '/admin/dashboard/temoignages'
    | '/api/admin/auth'
    | '/api/admin/galerie'
    | '/api/admin/reviews'
    | '/og-service/$slug/opengraph-image'
    | '/s/$channel/{-$campaign}'
    | '/admin/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/carte-verso-v2'
    | '/ds'
    | '/garde-chat-vannes'
    | '/garde-chien-vannes'
    | '/llms.txt'
    | '/opengraph-image'
    | '/post-parrainage-d'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/equitation-vannes'
    | '/garde-a-domicile-vannes'
    | '/pension-chat-vannes'
    | '/pension-chien-vannes'
    | '/promenade-chien-vannes'
    | '/visites-chat-vannes'
    | '/visites-chien-vannes'
    | '/admin/login'
    | '/api/contact'
    | '/uploads/$'
    | '/'
    | '/admin/dashboard/galerie'
    | '/admin/dashboard/temoignages'
    | '/api/admin/auth'
    | '/api/admin/galerie'
    | '/api/admin/reviews'
    | '/og-service/$slug/opengraph-image'
    | '/s/$channel/{-$campaign}'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/admin'
    | '/_public'
    | '/carte-verso-v2'
    | '/ds'
    | '/garde-chat-vannes'
    | '/garde-chien-vannes'
    | '/llms.txt'
    | '/opengraph-image'
    | '/post-parrainage-d'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/dashboard'
    | '/_public/equitation-vannes'
    | '/_public/garde-a-domicile-vannes'
    | '/_public/pension-chat-vannes'
    | '/_public/pension-chien-vannes'
    | '/_public/promenade-chien-vannes'
    | '/_public/visites-chat-vannes'
    | '/_public/visites-chien-vannes'
    | '/admin/login'
    | '/api/contact'
    | '/uploads/$'
    | '/_public/'
    | '/admin/dashboard/galerie'
    | '/admin/dashboard/temoignages'
    | '/api/admin/auth'
    | '/api/admin/galerie'
    | '/api/admin/reviews'
    | '/og-service/$slug/opengraph-image'
    | '/s/$channel/{-$campaign}'
    | '/admin/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  CarteVersoV2Route: typeof CarteVersoV2Route
  DsRoute: typeof DsRoute
  GardeChatVannesRoute: typeof GardeChatVannesRoute
  GardeChienVannesRoute: typeof GardeChienVannesRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OpengraphImageRoute: typeof OpengraphImageRoute
  PostParrainageDRoute: typeof PostParrainageDRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiContactRoute: typeof ApiContactRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
  ApiAdminAuthRoute: typeof ApiAdminAuthRoute
  ApiAdminGalerieRoute: typeof ApiAdminGalerieRoute
  ApiAdminReviewsRoute: typeof ApiAdminReviewsRoute
  OgServiceSlugOpengraphImageRoute: typeof OgServiceSlugOpengraphImageRoute
  SChannelChar123CampaignChar125Route: typeof SChannelChar123CampaignChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-parrainage-d': {
      id: '/post-parrainage-d'
      path: '/post-parrainage-d'
      fullPath: '/post-parrainage-d'
      preLoaderRoute: typeof PostParrainageDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opengraph-image': {
      id: '/opengraph-image'
      path: '/opengraph-image'
      fullPath: '/opengraph-image'
      preLoaderRoute: typeof OpengraphImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garde-chien-vannes': {
      id: '/garde-chien-vannes'
      path: '/garde-chien-vannes'
      fullPath: '/garde-chien-vannes'
      preLoaderRoute: typeof GardeChienVannesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garde-chat-vannes': {
      id: '/garde-chat-vannes'
      path: '/garde-chat-vannes'
      fullPath: '/garde-chat-vannes'
      preLoaderRoute: typeof GardeChatVannesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds': {
      id: '/ds'
      path: '/ds'
      fullPath: '/ds'
      preLoaderRoute: typeof DsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte-verso-v2': {
      id: '/carte-verso-v2'
      path: '/carte-verso-v2'
      fullPath: '/carte-verso-v2'
      preLoaderRoute: typeof CarteVersoV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/visites-chien-vannes': {
      id: '/_public/visites-chien-vannes'
      path: '/visites-chien-vannes'
      fullPath: '/visites-chien-vannes'
      preLoaderRoute: typeof PublicVisitesChienVannesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/visites-chat-vannes': {
      id: '/_public/visites-chat-vannes'
      path: '/visites-chat-vannes'
      fullPath: '/visites-chat-vannes'
      preLoaderRoute: typeof PublicVisitesChatVannesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/promenade-chien-vannes': {
      id: '/_public/promenade-chien-vannes'
      path: '/promenade-chien-vannes'
      fullPath: '/promenade-chien-vannes'
      preLoaderRoute: typeof PublicPromenadeChienVannesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pension-chien-vannes': {
      id: '/_public/pension-chien-vannes'
      path: '/pension-chien-vannes'
      fullPath: '/pension-chien-vannes'
      preLoaderRoute: typeof PublicPensionChienVannesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pension-chat-vannes': {
      id: '/_public/pension-chat-vannes'
      path: '/pension-chat-vannes'
      fullPath: '/pension-chat-vannes'
      preLoaderRoute: typeof PublicPensionChatVannesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/garde-a-domicile-vannes': {
      id: '/_public/garde-a-domicile-vannes'
      path: '/garde-a-domicile-vannes'
      fullPath: '/garde-a-domicile-vannes'
      preLoaderRoute: typeof PublicGardeADomicileVannesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/equitation-vannes': {
      id: '/_public/equitation-vannes'
      path: '/equitation-vannes'
      fullPath: '/equitation-vannes'
      preLoaderRoute: typeof PublicEquitationVannesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/s/$channel/{-$campaign}': {
      id: '/s/$channel/{-$campaign}'
      path: '/s/$channel/{-$campaign}'
      fullPath: '/s/$channel/{-$campaign}'
      preLoaderRoute: typeof SChannelChar123CampaignChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-service/$slug/opengraph-image': {
      id: '/og-service/$slug/opengraph-image'
      path: '/og-service/$slug/opengraph-image'
      fullPath: '/og-service/$slug/opengraph-image'
      preLoaderRoute: typeof OgServiceSlugOpengraphImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reviews': {
      id: '/api/admin/reviews'
      path: '/api/admin/reviews'
      fullPath: '/api/admin/reviews'
      preLoaderRoute: typeof ApiAdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/galerie': {
      id: '/api/admin/galerie'
      path: '/api/admin/galerie'
      fullPath: '/api/admin/galerie'
      preLoaderRoute: typeof ApiAdminGalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth': {
      id: '/api/admin/auth'
      path: '/api/admin/auth'
      fullPath: '/api/admin/auth'
      preLoaderRoute: typeof ApiAdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/temoignages': {
      id: '/admin/dashboard/temoignages'
      path: '/temoignages'
      fullPath: '/admin/dashboard/temoignages'
      preLoaderRoute: typeof AdminDashboardTemoignagesRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/galerie': {
      id: '/admin/dashboard/galerie'
      path: '/galerie'
      fullPath: '/admin/dashboard/galerie'
      preLoaderRoute: typeof AdminDashboardGalerieRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
  }
}

interface AdminDashboardRouteRouteChildren {
  AdminDashboardGalerieRoute: typeof AdminDashboardGalerieRoute
  AdminDashboardTemoignagesRoute: typeof AdminDashboardTemoignagesRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardGalerieRoute: AdminDashboardGalerieRoute,
  AdminDashboardTemoignagesRoute: AdminDashboardTemoignagesRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PublicRouteChildren {
  PublicEquitationVannesRoute: typeof PublicEquitationVannesRoute
  PublicGardeADomicileVannesRoute: typeof PublicGardeADomicileVannesRoute
  PublicPensionChatVannesRoute: typeof PublicPensionChatVannesRoute
  PublicPensionChienVannesRoute: typeof PublicPensionChienVannesRoute
  PublicPromenadeChienVannesRoute: typeof PublicPromenadeChienVannesRoute
  PublicVisitesChatVannesRoute: typeof PublicVisitesChatVannesRoute
  PublicVisitesChienVannesRoute: typeof PublicVisitesChienVannesRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicEquitationVannesRoute: PublicEquitationVannesRoute,
  PublicGardeADomicileVannesRoute: PublicGardeADomicileVannesRoute,
  PublicPensionChatVannesRoute: PublicPensionChatVannesRoute,
  PublicPensionChienVannesRoute: PublicPensionChienVannesRoute,
  PublicPromenadeChienVannesRoute: PublicPromenadeChienVannesRoute,
  PublicVisitesChatVannesRoute: PublicVisitesChatVannesRoute,
  PublicVisitesChienVannesRoute: PublicVisitesChienVannesRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  CarteVersoV2Route: CarteVersoV2Route,
  DsRoute: DsRoute,
  GardeChatVannesRoute: GardeChatVannesRoute,
  GardeChienVannesRoute: GardeChienVannesRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OpengraphImageRoute: OpengraphImageRoute,
  PostParrainageDRoute: PostParrainageDRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiContactRoute: ApiContactRoute,
  UploadsSplatRoute: UploadsSplatRoute,
  ApiAdminAuthRoute: ApiAdminAuthRoute,
  ApiAdminGalerieRoute: ApiAdminGalerieRoute,
  ApiAdminReviewsRoute: ApiAdminReviewsRoute,
  OgServiceSlugOpengraphImageRoute: OgServiceSlugOpengraphImageRoute,
  SChannelChar123CampaignChar125Route: SChannelChar123CampaignChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
